In [1]:
import cv2
import dlib
import numpy as np
import os
import imutils

In [2]:

os.chdir("D:\Documents\Semester 6\Deep Learning and Neural Networks\Project\Datasets\MaskTest")
path = "D:\Documents\Semester 6\Deep Learning and Neural Networks\Project\Datasets\MaskTest\4.png"

color_blue = (239,207,137)
color_cyan = (255,200,0)
color_black = (0, 0, 0)

In [4]:
img= cv2.imread("D:\Documents\Semester 6\Deep Learning and Neural Networks\Project\group.jpg")
img = imutils.resize(img, width = 500)
gray=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(img)

[[[235 237 237]
  [246 248 248]
  [249 251 251]
  ...
  [185 172 146]
  [180 167 141]
  [177 164 138]]

 [[235 237 237]
  [246 248 248]
  [249 251 251]
  ...
  [187 174 148]
  [183 170 144]
  [180 167 141]]

 [[235 237 237]
  [246 248 248]
  [249 251 251]
  ...
  [190 177 151]
  [186 173 147]
  [182 169 143]]

 ...

 [[  1   1   1]
  [  1   1   1]
  [  1   1   1]
  ...
  [ 35  42  79]
  [ 20  29  60]
  [  6  16  42]]

 [[  1   1   1]
  [  1   1   1]
  [  1   1   1]
  ...
  [ 34  39  75]
  [ 20  26  57]
  [  9  17  43]]

 [[  1   1   1]
  [  1   1   1]
  [  1   1   1]
  ...
  [ 28  32  68]
  [ 15  21  50]
  [  8  16  40]]]


In [5]:
#  initialization dlib Face detector 
detector = dlib.get_frontal_face_detector()
"""
Detect faces in grayscale images and create an object - Stores a list of coordinates for the bounding rectangle
In the second parameter “1” Indicates that the image should be sampled up 1 Time . 
This makes the image bigger , And allow us to detect more faces
"""
faces = detector(gray, 8)
#faces = detector(gray, 1)
#  Print the coordinates of the bounding rectangle 
print(faces)
print("Number of faces detected: ", len(faces))
"""
#  Use for Loop to extract specific coordinates (x1,x2,y1,y2)
for face in faces:
  x1 = face.left()
  y1 = face.top()
  x2 = face.right()
  y2 = face.bottom()
  #  Draw a rectangle around the detected face
  cv2.rectangle(img, (x1,y1), (x2,y2),(0,255,0),3)
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()
"""

rectangles[[(201, 74) (237, 110)], [(117, 94) (153, 130)], [(395, 89) (439, 132)], [(69, 108) (112, 151)], [(145, 50) (181, 86)], [(31, 36) (74, 79)], [(319, 55) (362, 98)], [(261, 34) (297, 70)]]
Number of faces detected:  8


'\n#  Use for Loop to extract specific coordinates (x1,x2,y1,y2)\nfor face in faces:\n  x1 = face.left()\n  y1 = face.top()\n  x2 = face.right()\n  y2 = face.bottom()\n  #  Draw a rectangle around the detected face\n  cv2.rectangle(img, (x1,y1), (x2,y2),(0,255,0),3)\ncv2.imshow("image", img)\ncv2.waitKey(0)\ncv2.destroyAllWindows()\n'

In [6]:
#  File path 
p = "D:\Documents\Semester 6\Deep Learning and Neural Networks\Project\Datasets\shape_predictor_68_face_landmarks.dat"
#  initialization dlib Predictor of 
predictor = dlib.shape_predictor(p)
#  Use predictors to get shapes 
for face in faces:
    landmarks = predictor(gray, face)
    # for n in range(0,68):
    #     x = landmarks.part(n).x
    #     y = landmarks.part(n).y
    #     img_landmark = cv2.circle(img, (x, y), 4, (0, 0, 255), -1)

In [7]:



#  Use input() Function to obtain the mask type and mask color according to user needs 
choice1 = input("Please select the choice of mask color\nEnter 1 for blue\nEnter 2 for black:\n")
choice1 = int(choice1)
if choice1 == 1:
    choice1 = color_blue
    print('You selected mask color = blue')
elif choice1 == 2:
    choice1 = color_black
    print('You selected mask color = black')
else:
    print("invalid selection, please select again.")
    input("Please select the choice of mask color\nEnter 1 for blue\nEnter 2 for black :\n")
choice2 = input("Please enter choice of mask type coverage \nEnter 1 for high \nEnter 2 for medium \nEnter 3 for low :\n")
choice2 = int(choice2)
if choice2 == 1:
    # choice2 = fmask_a
    print(f'You chosen wide, high coverage mask')
elif choice2 == 2:
    # choice2 = fmask_c
    print(f'You chosen wide, medium coverage mask')
elif choice2 == 3:
    # choice2 = fmask_e
    print(f'You chosen wide, low coverage mask')
else:
    print("invalid selection, please select again.")
    input("Please enter choice of mask type coverage \nEnter 1 for high \nEnter 2 for medium \nEnter 3 for low :\n")
# print(choice2)


#---------------------------------------------------------------------------------------------------

points = []
for i in range(1, 16):
    point = [landmarks.part(i).x, landmarks.part(i).y]
    points.append(point)
# print(points)
#  wide , High coverage masks 
mask_a = [((landmarks.part(42).x), (landmarks.part(15).y)),
          ((landmarks.part(27).x), (landmarks.part(27).y)),
          ((landmarks.part(39).x), (landmarks.part(1).y))]
#  wide , In the middle of the mask 
mask_c = [((landmarks.part(29).x), (landmarks.part(29).y))]
#  wide 、 Low coverage masks 
mask_e = [((landmarks.part(35).x), (landmarks.part(35).y)),
          ((landmarks.part(34).x), (landmarks.part(34).y)),
          ((landmarks.part(33).x), (landmarks.part(33).y)),
          ((landmarks.part(32).x), (landmarks.part(32).y)),
          ((landmarks.part(31).x), (landmarks.part(31).y))]
fmask_a = points + mask_a
fmask_c = points + mask_c
fmask_e = points + mask_e
# mask_type = {1: fmask_a, 2: fmask_c, 3: fmask_e}
# mask_type[choice2]
#  Use Python OpenCV - cv2.polylines() Method is [mask_type] Draw the mask outline :
# fmask_a = wide, high coverage mask,
# fmask_c = wide, medium coverage mask,
# fmask_e  = wide, low coverage mask
fmask_a = np.array(fmask_a, dtype=np.int32)
fmask_c = np.array(fmask_c, dtype=np.int32)
fmask_e = np.array(fmask_e, dtype=np.int32)
mask_type = {1: fmask_a, 2: fmask_c, 3: fmask_e}
mask_type[choice2]
#  Change parameters [mask_type] and color_type For various combinations 
img2 = cv2.polylines(img, [mask_type[choice2]], True, choice1, thickness=2, lineType=cv2.LINE_8)
#  Use Python OpenCV - cv2.fillPoly() How to fill the mask 
#  Change parameters [mask_type] and color_type For various combinations 
img3 = cv2.fillPoly(img2, [mask_type[choice2]], choice1, lineType=cv2.LINE_AA)
# cv2.imshow("image with mask outline", img2)
cv2.imshow("image with mask", img3)
#  Save the output file for the test 
outputNameofImage = "D:\Documents\Semester 6\Deep Learning and Neural Networks\Project\Datasets\MaskTest\Masked\imagetest2.jpg"
print("Saving output image to", outputNameofImage)
cv2.imwrite(outputNameofImage, img3)

#---------------------------------------------------------------------------------------------------

You selected mask color = black
You chosen wide, medium coverage mask
Saving output image to D:\Documents\Semester 6\Deep Learning and Neural Networks\Project\Datasets\MaskTest\Masked\imagetest2.jpg


True