In [44]:
import cv2
import dlib
import numpy as np
import os
import imutils
import matplotlib.pyplot as plt

In [45]:
# os.chdir("")
path = "D:\Documents\Semester 6\Deep Learning and Neural Networks\Project\Datasets\\Dataset_400\\anger_400\\anger_136.png"

color_blue = (239,207,137)

In [46]:
img= cv2.imread(path)
#if (img is None):
 #   img=np.array(img,dtype=np.int32)
img = imutils.resize(img, width = 500)
gray=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(img)

[[[ 50  50  50]
  [ 50  50  50]
  [ 50  50  50]
  ...
  [219 219 219]
  [219 219 219]
  [219 219 219]]

 [[ 50  50  50]
  [ 50  50  50]
  [ 50  50  50]
  ...
  [219 219 219]
  [219 219 219]
  [219 219 219]]

 [[ 50  50  50]
  [ 50  50  50]
  [ 50  50  50]
  ...
  [219 219 219]
  [219 219 219]
  [219 219 219]]

 ...

 [[ 36  36  36]
  [ 36  36  36]
  [ 36  36  36]
  ...
  [  6   6   6]
  [  6   6   6]
  [  6   6   6]]

 [[ 36  36  36]
  [ 36  36  36]
  [ 36  36  36]
  ...
  [  6   6   6]
  [  6   6   6]
  [  6   6   6]]

 [[ 36  36  36]
  [ 36  36  36]
  [ 36  36  36]
  ...
  [  6   6   6]
  [  6   6   6]
  [  6   6   6]]]


In [47]:
detector = dlib.get_frontal_face_detector()
faces = detector(gray, 1)

#print(faces)
#print("Number of faces detected: ", len(faces))

In [48]:
p = "D:\Documents\Semester 6\Deep Learning and Neural Networks\Project\Datasets\shape_predictor_68_face_landmarks.dat"
predictor = dlib.shape_predictor(p)

for face in faces:
    landmarks = predictor(gray, face)

In [50]:
choice1 = color_blue

points = []
for i in range(1, 16):
    point = [landmarks.part(i).x, landmarks.part(i).y]
    points.append(point)

mask_c = [((landmarks.part(29).x), (landmarks.part(29).y))]

fmask_c = points + mask_c
fmask_c = np.array(fmask_c, dtype=np.int32)
img2 = cv2.polylines(img, [fmask_c], True, choice1, thickness=2, lineType=cv2.LINE_8)
img3 = cv2.fillPoly(img2, [fmask_c], choice1, lineType=cv2.LINE_AA)

plt.imshow(img3)


if(landmarks.part(20).y>landmarks.part(25).y):
    pointA1=[((landmarks.part(1).x-20),(landmarks.part(20).y)-50)]
else:
    pointA1=[((landmarks.part(1).x-20),(landmarks.part(25).y)-50)]
pointB1=[((landmarks.part(16).x+20),(landmarks.part(31).y-40))]

cropWindow2=pointA1+pointB1
cropWindow2=np.array(cropWindow2,dtype=np.int32)

print(landmarks.part(20).y)
print(landmarks.part(25).y)
print(cropWindow2)

x1 = cropWindow2[0][0] # x1
y1 = cropWindow2[0][1] # y1

x2 = cropWindow2[1][0] # x2
y2 = cropWindow2[1][1] # y2

print(x1,y1)
print(y1,y2)

if (x1 < 0 or x2 < 0 or y1 < 0 or y2 < 0):
  if x1 < 0:
    x1 = 0
  elif y1 < 0:
    y1 = 0
  elif x2 < 0:
    x2 = 0
  else:
    y2 = 0

# crop_img2=img3[cropWindow2[0][1]:cropWindow2[1][1],cropWindow2[0][0]:cropWindow2[1][0]]

crop_img2 = img3[y1:y2,x1:x2]

plt.imshow(crop_img2)

#  Output
#outputNameofImage = "D:\Documents\Semester 6\Deep Learning and Neural Networks\Project\Datasets\MaskTest - Review\Masked\Test-Crop.jpg"
#print("Saving output image to", outputNameofImage)
#cv2.imwrite(outputNameofImage, img3)


NameError: name 'landmarks' is not defined